platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'AlamofireImage', '~> 2.0'
pod 'Crashlytics'
pod 'Fabric'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'Google/Analytics', '~> 1.0.0'
pod 'MBProgressHUD', '~> 0.9.1'
