source 'https://rubygems.org'
ruby "2.3.0"

# Rails
gem 'rails', '4.2.5'

# Postgres
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Caching
gem 'dalli'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# jQuery
gem 'jquery-rails'

# JSON APIs
gem 'jbuilder', '~> 2.0'
gem 'jsonapi-resources', '0.4.4'

# CoffeeScript
gem 'coffee-rails', '~> 4.1.0'

# Login system
gem 'devise', '3.5.3'
gem 'devise-async', '0.10.1'

# Background Jobs
gem 'sidekiq'

# Authentication
gem "cancancan"

# Used to extract and normalize URLs from messages
gem 'postrank-uri'

# Facebook Authentication
gem 'omniauth-facebook'

# Facebook API
gem "koala", "~> 2.2"

# Uploading files
gem 'paperclip', github: 'thoughtbot/paperclip'

# Amazon Web Services
gem 'aws-s3', '0.6.3'
gem 'aws-sdk', '1.60.2'

# Search Capabilities
gem 'elasticsearch-model'
gem 'elasticsearch-rails'

# Emails by Mandrill
gem 'mandrill-api'

# SMS by Twilio
gem 'twilio-ruby'

# Exception Notifications
gem 'exception_notification'
gem 'slack-notifier'

# Pagination Gem
gem 'kaminari'

# Slug management
gem 'friendly_id'

# Database View Support
gem 'scenic'

# Apple Push Notifications
gem 'houston'

# Server
gem 'unicorn'
gem 'rack-timeout'

gem 'flash_render'
gem 'rubyzip', '>= 1.0.0'

group :development do
  # Supporting gem for Rails Panel (Google Chrome extension for Rails development)
  gem 'meta_request'
  # Preview email in the browser instead of sending it.
  gem 'letter_opener'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

group :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'capybara'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'byebug'
end

group :production do
  # Something Heroku requires for assets?
  gem 'rails_12factor'
  # App Monitoring
  gem 'skylight', '~> 0.10.3'
end
