# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

if Rails.env.development?
  annotate_gem = Gem::Specification.find_by_name("annotate")
  Dir["#{annotate_gem.full_gem_path}/**/tasks/**/*.rake"].each {|ext| load ext} if annotate_gem
end
